# Challenge 3

In this challenge we will work on the `Orders` data set. In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

## Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [1]:
# import required libraries
import numpy as np
import pandas as pd

Next, extract and import `Orders` dataset into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [2]:
orders = pd.read_csv("Orders.csv")
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [3]:
# 1 Group by CustomerID and sum the amount_spent
customer_spend = orders.groupby('CustomerID')['amount_spent'].sum().reset_index()

customer_spend.head()

   CustomerID  amount_spent
0       12346      77183.60
1       12347       4310.00
2       12348       1797.24
3       12349       1757.55
4       12350        334.40

In [4]:
vip_cutoff = customer_spend['amount_spent'].quantile(0.95)
preferred_cutoff = customer_spend['amount_spent'].quantile(0.75)

print(f"VIP Threshold: ${vip_cutoff:.2f}")
print(f"Preferred Threshold: ${preferred_cutoff:.2f}")

VIP Threshold: $5840.18
Preferred Threshold: $1661.64

In [8]:
# 1. Define the function with your specific logic
def categorize_customer(spend):
    if spend >= vip_cutoff:
        return 'VIP'
    elif spend >= preferred_cutoff:
        return 'Preferred'
    else:
        return 'Regular'


customer_spend['Label'] = customer_spend['amount_spent'].apply(categorize_customer)

customer_spend.head()

   CustomerID  amount_spent      Label
0       12346      77183.60        VIP
1       12347       4310.00  Preferred
2       12348       1797.24  Preferred
3       12349       1757.55  Preferred
4       12350        334.40    Regular

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

## Q2: How to identify which country has the most VIP Customers?

In [12]:
customer_spend = orders.groupby('CustomerID')['amount_spent'].sum().reset_index()

In [13]:
customer_countries = orders[['CustomerID', 'Country']].drop_duplicates()

In [14]:
customer_spend = pd.merge(customer_spend, customer_countries, on='CustomerID', how='left')
customer_spend.head()

   CustomerID  amount_spent         Country
0       12346      77183.60  United Kingdom
1       12347       4310.00         Iceland
2       12348       1797.24         Finland
3       12349       1757.55           Italy
4       12350        334.40          Norway

In [16]:
customer_spend['Label'] = customer_spend['amount_spent'].apply(categorize_customer)
customer_spend.head()

   CustomerID  amount_spent         Country      Label
0       12346      77183.60  United Kingdom        VIP
1       12347       4310.00         Iceland  Preferred
2       12348       1797.24         Finland  Preferred
3       12349       1757.55           Italy  Preferred
4       12350        334.40          Norway    Regular

In [17]:
vips = customer_spend[customer_spend['Label'] == 'VIP']

vips['Country'].value_counts().head()

Country
United Kingdom    177
Germany            10
France              9
Switzerland         3
Australia           2
Name: count, dtype: int64

## Q3: How to identify which country has the most VIP+Preferred Customers combined?

In [18]:
# Filter for VIP OR Preferred
combined = customer_spend[customer_spend['Label'].isin(['VIP', 'Preferred'])]

combined['Country'].value_counts().head()

Country
United Kingdom    932
Germany            39
France             29
Belgium            12
Switzerland         9
Name: count, dtype: int64