# Challenge 3

In this challenge we will work on the `Orders` data set. In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

## Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [4]:
# import required libraries
import numpy as np
import pandas as pd
import zipfile
import os

Next, extract and import `Orders` dataset into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [6]:
os.listdir('.')

['.ipynb_checkpoints', 'main.ipynb', 'Orders.csv', 'Orders.zip']

In [3]:
zip_path = 'Orders.zip'
extract_to = '.' # current working directory

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

In [7]:
os.listdir('.')

['.ipynb_checkpoints', 'main.ipynb', 'Orders.csv', 'Orders.zip']

In [8]:
orders = pd.read_csv('Orders.csv')

In [9]:
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [11]:
orders.shape

(397924, 14)

In [12]:
orders.dtypes

Unnamed: 0        int64
InvoiceNo         int64
StockCode        object
year              int64
month             int64
day               int64
hour              int64
Description      object
Quantity          int64
InvoiceDate      object
UnitPrice       float64
CustomerID        int64
Country          object
amount_spent    float64
dtype: object

In [13]:
orders.isna().sum()

Unnamed: 0      0
InvoiceNo       0
StockCode       0
year            0
month           0
day             0
hour            0
Description     0
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID      0
Country         0
amount_spent    0
dtype: int64

In [14]:
orders.duplicated().sum()

0

Data seems to clean, no data quality issues identified

In [18]:
orders['CustomerID'].nunique() # unique customer count

4339

In [24]:
customer_revenue = orders \
    .groupby('CustomerID') \
    .agg({'amount_spent' : 'sum'})

In [27]:
customer_revenue.head()

            amount_spent
CustomerID
12346           77183.60
12347            4310.00
12348            1797.24
12349            1757.55
12350             334.40

In [55]:
customer_revenue['percentile'] = pd.qcut(customer_revenue['amount_spent'], 20, labels=range(5, 101, 5))

In [59]:
customer_revenue.head()

            amount_spent percentile
CustomerID
12346           77183.60        100
12347            4310.00         95
12348            1797.24         80
12349            1757.55         80
12350             334.40         30

In [60]:
customer_revenue.value_counts('percentile').sort_index()

# eqial bins as expected

percentile
5      217
10     217
15     217
20     217
25     217
30     217
35     217
40     217
45     217
50     217
55     216
60     217
65     217
70     218
75     216
80     217
85     217
90     217
95     217
100    217
Name: count, dtype: int64

In [66]:
customer_revenue['percentile'].dtype

CategoricalDtype(categories=range(5, 101, 5), ordered=True, categories_dtype=int64)

In [69]:
customer_revenue.head()

            amount_spent percentile
CustomerID
12346           77183.60        100
12347            4310.00         95
12348            1797.24         80
12349            1757.55         80
12350             334.40         30

In [67]:
def customer_priority(row):
    if 75 <= row['percentile'] <= 95:
        return 'Preffered customer'
    elif row['percentile'] > 95:
        return 'VIP customer'
    else:
        return 'Unclassified'

In [71]:
customer_revenue['classification'] = customer_revenue.apply(customer_priority, axis=1)

In [72]:
customer_revenue

            amount_spent percentile      classification
CustomerID
12346           77183.60        100        VIP customer
12347            4310.00         95  Preffered customer
12348            1797.24         80  Preffered customer
12349            1757.55         80  Preffered customer
12350             334.40         30        Unclassified
...                  ...        ...                 ...
18280             180.60         15        Unclassified
18281              80.82          5        Unclassified
18282             178.05         15        Unclassified
18283            2094.88         85  Preffered customer
18287            1837.28         80  Preffered customer

[4339 rows x 3 columns]

In [73]:
customer_revenue.value_counts('classification')

classification
Unclassified          3038
Preffered customer    1084
VIP customer           217
Name: count, dtype: int64

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

## Q2: How to identify which country has the most VIP Customers?

In [79]:
orders[['CustomerID', 'Country']].drop_duplicates()

        CustomerID         Country
0            17850  United Kingdom
9            13047  United Kingdom
26           12583          France
46           13748  United Kingdom
65           15100  United Kingdom
...            ...             ...
394965       13436  United Kingdom
395041       15520  United Kingdom
395777       13298  United Kingdom
396506       14569  United Kingdom
397783       12713         Germany

[4347 rows x 2 columns]

In [81]:
orders[['CustomerID']].nunique()

CustomerID    4339
dtype: int64

In [82]:
# a small subset of customers made orders from multiple countries

In [118]:
customer_countries = orders.groupby(['CustomerID']).agg({'Country' : 'nunique'})
int_cust = customer_countries.query('Country > 1').index

In [120]:
orders \
    .loc[:, ['CustomerID', 'Country']] \
    .drop_duplicates() \
    .query('CustomerID.isin(@int_cust)') \
    .sort_values('CustomerID')

        CustomerID      Country
19239        12370       Cyprus
23215        12370      Austria
121887       12394      Belgium
276556       12394      Denmark
23354        12417      Belgium
116553       12417        Spain
37687        12422    Australia
168243       12422  Switzerland
13134        12429      Denmark
114255       12429      Austria
195          12431    Australia
58027        12431      Belgium
57107        12455       Cyprus
147386       12455        Spain
107170       12457  Switzerland
246989       12457       Cyprus

In [126]:
customer_country = orders[['CustomerID', 'Country']].drop_duplicates()

customer_country

        CustomerID         Country
0            17850  United Kingdom
9            13047  United Kingdom
26           12583          France
46           13748  United Kingdom
65           15100  United Kingdom
...            ...             ...
394965       13436  United Kingdom
395041       15520  United Kingdom
395777       13298  United Kingdom
396506       14569  United Kingdom
397783       12713         Germany

[4347 rows x 2 columns]

In [130]:
customer_revenue = customer_revenue.reset_index()

In [131]:
customer_revenue

      CustomerID  amount_spent percentile      classification
0          12346      77183.60        100        VIP customer
1          12347       4310.00         95  Preffered customer
2          12348       1797.24         80  Preffered customer
3          12349       1757.55         80  Preffered customer
4          12350        334.40         30        Unclassified
...          ...           ...        ...                 ...
4334       18280        180.60         15        Unclassified
4335       18281         80.82          5        Unclassified
4336       18282        178.05         15        Unclassified
4337       18283       2094.88         85  Preffered customer
4338       18287       1837.28         80  Preffered customer

[4339 rows x 4 columns]

In [133]:
country_class = pd.merge(
    left=customer_revenue,
    right=customer_country,
    on='CustomerID',
    how='left'
)

In [138]:
country_class \
    .query('classification in ["VIP customer"]') \
    .groupby(['Country']).agg({'classification' : 'count'}) \
    .sort_values('classification', ascending=False)

                 classification
Country
United Kingdom              177
Germany                      10
France                        9
Switzerland                   3
Spain                         2
Portugal                      2
Australia                     2
EIRE                          2
Japan                         2
Finland                       1
Belgium                       1
Netherlands                   1
Norway                        1
Denmark                       1
Singapore                     1
Cyprus                        1
Sweden                        1
Channel Islands               1

## Q3: How to identify which country has the most VIP+Preferred Customers combined?

In [139]:
country_class \
    .query('classification in ["VIP customer", "Preffered customer"]') \
    .groupby(['Country']).agg({'classification' : 'count'}) \
    .sort_values('classification', ascending=False)

                 classification
Country
United Kingdom             1132
Germany                      42
France                       30
Belgium                      12
Switzerland                  11
Spain                         9
Channel Islands               7
Portugal                      7
Norway                        7
Austria                       5
Australia                     5
Italy                         5
Finland                       5
Cyprus                        4
Japan                         4
Netherlands                   3
Denmark                       3
EIRE                          3
Israel                        2
Sweden                        2
Malta                         1
Lithuania                     1
Iceland                       1
Poland                        1
Lebanon                       1
Singapore                     1
Canada                        1
USA                           1
Greece                        1