# Challenge 3

In this challenge we will work on the `Orders` data set. In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

## Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [8]:
# import required libraries
import numpy as np
import pandas as pd

Next, extract and import `Orders` dataset into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [9]:
orders = pd.read_csv("Orders.csv")

In [10]:
orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010.0,12.0,3.0,8.0,white hanging heart t-light holder,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,1,536365,71053,2010.0,12.0,3.0,8.0,white metal lantern,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,2,536365,84406B,2010.0,12.0,3.0,8.0,cream cupid hearts coat hanger,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,3,536365,84029G,2010.0,12.0,3.0,8.0,knitted union flag hot water bottle,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,4,536365,84029E,2010.0,12.0,3.0,8.0,red woolly hottie white heart.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [11]:
df_orders = pd.DataFrame(orders)

In [12]:
df_orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010.0,12.0,3.0,8.0,white hanging heart t-light holder,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,1,536365,71053,2010.0,12.0,3.0,8.0,white metal lantern,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,2,536365,84406B,2010.0,12.0,3.0,8.0,cream cupid hearts coat hanger,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,3,536365,84029G,2010.0,12.0,3.0,8.0,knitted union flag hot water bottle,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,4,536365,84029E,2010.0,12.0,3.0,8.0,red woolly hottie white heart.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [13]:
aggregated_spent = df_orders.groupby(['CustomerID'])['amount_spent'].sum().reset_index()

In [14]:
print(df_orders.columns)

Index(['Unnamed: 0', 'InvoiceNo', 'StockCode', 'year', 'month', 'day', 'hour',
       'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID',
       'Country', 'amount_spent'],
      dtype='object')

In [15]:
q95 = aggregated_spent['amount_spent'].quantile(0.95)
q75 = aggregated_spent['amount_spent'].quantile(0.75)

In [16]:
vip_customers = aggregated_spent[aggregated_spent['amount_spent'] > q95]

In [17]:
preferred_customers = aggregated_spent[
    (aggregated_spent['amount_spent'] > q75) & (aggregated_spent['amount_spent'] <= q95)
]

In [27]:
aggregated_spent.loc[aggregated_spent['CustomerID'].isin(vip_customers['CustomerID']), 'label'] = "VIP"
aggregated_spent.loc[aggregated_spent['CustomerID'].isin(preferred_customers['CustomerID']), 'label'] = "Preferred"

In [30]:
print("\nLabeled Customers:")
print(aggregated_spent)

Labeled Customers:
      CustomerID  amount_spent      label
0        12346.0      77183.60        VIP
1        12347.0       1187.18  Preferred
2        12348.0       1120.24  Preferred
3        12356.0       2271.62  Preferred
4        12359.0        547.50        NaN
...          ...           ...        ...
1266     18245.0        365.73        NaN
1267     18259.0        376.30        NaN
1268     18260.0        787.77  Preferred
1269     18269.0        168.60        NaN
1270     18283.0        215.00        NaN

[1271 rows x 3 columns]

In [58]:
aggregated_spent

      CustomerID  amount_spent      label
0        12346.0      77183.60        VIP
1        12347.0       1187.18  Preferred
2        12348.0       1120.24  Preferred
3        12356.0       2271.62  Preferred
4        12359.0        547.50        NaN
...          ...           ...        ...
1266     18245.0        365.73        NaN
1267     18259.0        376.30        NaN
1268     18260.0        787.77  Preferred
1269     18269.0        168.60        NaN
1270     18283.0        215.00        NaN

[1271 rows x 3 columns]

In [38]:
df_orders[df_orders["CustomerID"] == 12346.0]

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
37126,61619,541431,23166,2011.0,1.0,2.0,10.0,medium ceramic top storage jar,74215.0,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.6

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

## Q2: How to identify which country has the most VIP Customers?

In [71]:
merged_df = pd.merge(df_orders, aggregated_spent, on='CustomerID', how='left')

In [89]:
merged_df[merged_df["label"] == "VIP"]

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent_x,amount_spent_y,label
0,0,536365,85123A,2010.0,12.0,3.0,8.0,white hanging heart t-light holder,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,5391.21,VIP
1,1,536365,71053,2010.0,12.0,3.0,8.0,white metal lantern,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,5391.21,VIP
2,2,536365,84406B,2010.0,12.0,3.0,8.0,cream cupid hearts coat hanger,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,5391.21,VIP
3,3,536365,84029G,2010.0,12.0,3.0,8.0,knitted union flag hot water bottle,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,5391.21,VIP
4,4,536365,84029E,2010.0,12.0,3.0,8.0,red woolly hottie white heart.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,5391.21,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45277,74685,542519,22973,2011.0,1.0,5.0,12.0,children's circus parade mug,12.0,2011-01-28 12:19:00,1.65,15159.0,United Kingdom,19.80,2698.12,VIP
45278,74686,542519,22631,2011.0,1.0,5.0,12.0,circus parade lunch box,12.0,2011-01-28 12:19:00,1.95,15159.0,United Kingdom,23.40,2698.12,VIP
45279,74687,542519,22977,2011.0,1.0,5.0,12.0,dolly girl childrens egg cup,12.0,2011-01-28 12:19:00,1.25,15159.0,United Kingdom,15.00,2698.12,VIP
45280,74688,542519,22975,2011.0,1.0,5.0,12.0,spaceboy childrens egg cup,12.0,2011-01-28 12:19:00,1.25,15159.0,United Kingdom,15.00,2698.12,VIP
45281,74689,542519,22976,2011.0,1.0,5.0,12.0,circus parade childrens egg cup,12.0,2011-01-28 12:19:00,1.25,15159.0,United Kingdom,15.00,2698.12,VIP

In [91]:
vip_customers = merged_df[merged_df['label'] == 'VIP']

In [92]:
country_vip_counts = vip_customers.groupby('Country').size()

In [93]:
country_vip_counts.idxmax()

'United Kingdom'

## Q3: How to identify which country has the most VIP+Preferred Customers combined?

In [76]:
merged_df[merged_df["label"] == "Preferred"]

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent_x,amount_spent_y,label
26,26,536370,22728,2010.0,12.0,3.0,8.0,alarm clock bakelike pink,24.0,2010-12-01 08:45:00,3.75,12583.0,France,90.0,1586.02,Preferred
27,27,536370,22727,2010.0,12.0,3.0,8.0,alarm clock bakelike red,24.0,2010-12-01 08:45:00,3.75,12583.0,France,90.0,1586.02,Preferred
28,28,536370,22726,2010.0,12.0,3.0,8.0,alarm clock bakelike green,12.0,2010-12-01 08:45:00,3.75,12583.0,France,45.0,1586.02,Preferred
29,29,536370,21724,2010.0,12.0,3.0,8.0,panda and bunnies sticker sheet,12.0,2010-12-01 08:45:00,0.85,12583.0,France,10.2,1586.02,Preferred
30,30,536370,21883,2010.0,12.0,3.0,8.0,stars gift tape,24.0,2010-12-01 08:45:00,0.65,12583.0,France,15.6,1586.02,Preferred
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45399,74807,542527,22988,2011.0,1.0,5.0,12.0,soldiers egg cup,24.0,2011-01-28 12:48:00,1.25,17188.0,United Kingdom,30.0,1424.44,Preferred
45400,74808,542527,85059,2011.0,1.0,5.0,12.0,french enamel water basin,8.0,2011-01-28 12:48:00,1.25,17188.0,United Kingdom,10.0,1424.44,Preferred
45401,74809,542527,85054,2011.0,1.0,5.0,12.0,french enamel pot w lid,12.0,2011-01-28 12:48:00,1.25,17188.0,United Kingdom,15.0,1424.44,Preferred
45429,74840,542533,22781,2011.0,1.0,5.0,13.0,gumball magazine rack,12.0,2011-01-28 13:18:00,6.75,16019.0,United Kingdom,81.0,824.15,Preferred
45430,74841,542533,79321,2011.0,1.0,5.0,13.0,chilli lights,4.0,2011-01-28 13:18:00,4.95,16019.0,United Kingdom,19.8,824.15,Preferred

In [78]:
preferred_customers = merged_df[merged_df['label'] == 'Preferred']

In [79]:
country_preferred_counts = preferred_customers.groupby('Country').size()

In [80]:
country_preferred_counts

Country
Australia            24
Austria               8
Belgium              68
Cyprus               83
Denmark              20
EIRE                 39
Finland              23
France              470
Germany             576
Iceland              60
Italy                70
Lebanon              45
Lithuania            35
Poland               33
Portugal            176
Singapore            56
Spain               149
Switzerland          74
United Kingdom    12620
dtype: int64

In [81]:
country_vip_counts

Country
Australia           47
EIRE               468
France             203
Germany            220
Greece              32
Japan               49
Netherlands        290
Norway             147
Spain              195
Sweden              47
Switzerland        101
United Kingdom    6204
dtype: int64

In [82]:
combined_counts = country_preferred_counts + country_vip_counts

In [85]:
combined_counts

Country
Australia            71.0
Austria               NaN
Belgium               NaN
Cyprus                NaN
Denmark               NaN
EIRE                507.0
Finland               NaN
France              673.0
Germany             796.0
Greece                NaN
Iceland               NaN
Italy                 NaN
Japan                 NaN
Lebanon               NaN
Lithuania             NaN
Netherlands           NaN
Norway                NaN
Poland                NaN
Portugal              NaN
Singapore             NaN
Spain               344.0
Sweden                NaN
Switzerland         175.0
United Kingdom    18824.0
dtype: float64

In [88]:
combined_counts.idxmax()

'United Kingdom'